### ISSUE TITLE
Ingress deployment issue

### ISSUE THREAD

**Issue by Guillaume-Riviere** [algosup/2022-2023-project-2-santa-time-Project-5-group#78]
### **Describe the bug**

Ingress deployment fail because error or cert manager

### **To Reproduce**

1. Run the workflow

### **Expected behavior**

Should deploy the app and activate SSL on the cluster

### **Area**

Server / Cluster / SSL / Docker

### **Priority**

Critical

### **Machine**

/

### **Screenshots**

/

**Comment by tomondre** [comment]
You can try this: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

**Comment by PaulMarisOUMary** [comment]
We are using
https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/blob/ced7d5b6e61e4c337f1eb3a6c7a563a5b4570cee/.k8s/xmas-ingress.yml#L1-L27

**Comment by tomondre** [comment]
Try to remove the kubernetes.io/ingress.class: "nginx" annotation and redeploy :smile:

**Comment by PaulMarisOUMary** [comment]
The ingress is meant to use [cert-manager](https://cert-manager.io/docs/), so we can use the https.
We're a bit lost about it.

**Comment by tomondre** [comment]
I will try to look into it after work today :smile: . So the current error that is thrown in the pipeline is: 
Error from server (InternalError): error when creating "/tmp/xmas-ingress.yml": Internal error occurred: failed calling webhook.
Could you shell into one of your containers and run `nslookup quickstart-ingress-nginx-controller-admission.default.svc`?

**Comment by tomondre** [comment]
There is a difference between Ingress Controller and cert-manager. Ingress controller is used to help you forward the traffic to services and pods and cert-manager is often used to terminate ssl certificates on the ingress level - with nginx.
You can check out this article to have an understanding of the nginx with cert-manager: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes.
But I would advise you to deploy the resources via Helm Chart so that you don't need to setup every single resource manually - the Helm Chart helps you to create them at one deploy.

**Comment by tomondre** [comment]
I believe that the Nginx ingress controller is not installed in your cluster. This is a prerequisite for the ingress resource to work, so I would advise you to follow a tutorial on how to set it up. E.g.: https://spacelift.io/blog/kubernetes-ingress

**Comment by PaulMarisOUMary** [comment]
Thanks,
According to the [DigitalOcean tutorial on nginx-ingress](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes) you sent, I'm editing our manifests in [.k8s/](https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/tree/main/.k8s)

The controller seems to be created during the deployement.

I have however an additional constraint, we're using the automated deployment of Azure, we're deploying only with our manifests inside [.k8s/](https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/tree/main/.k8s).

**Comment by tomondre** [comment]
This looks good. Previously the error was `service "quickstart-ingress-nginx-controller-admission" not found ` and now it is: `no endpoints available for service "ingress-nginx-controller-admission" `

**Comment by PaulMarisOUMary** [comment]
I'm thinking about starting over, my workflow on azure had a different naming style, and when I changed many things in the (forked) [xmas-ressource.yml](https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/blob/main/.k8s/xmas-ressource.yml) it breaks few things.

By starting over I could change the naming style of my workflow on azure, and so I won't change the forked [xmas-ressource.yml](https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/blob/main/.k8s/xmas-ressource.yml).
I'll do it Soon™ (asap, I hope this evening)

**Comment by tomondre** [comment]
Okay, let me know if there is something that I can help with. Kubernetes has a super steep learning curve but you won't regret the journey :smile:

**Comment by PaulMarisOUMary** [comment]
To be honest, the "only reason" we're using the ingress is to finally be able to use **https** on our website.

I have "access", I mean have a report status, and can see few details and informations about:
LoadBalancer
- xmas-service
    - Pods
        - controller (image registry.k8s.io/ingress-nginx/controller:v1.5.1)

Deployment
- xmas-deployment
    - Pods
        - xmas (running with our custom image)

ClusterIP
- ingress-nginx-controller-admission
    - Pods
        - controller (image registry.k8s.io/ingress-nginx/controller:v1.5.1)
    - Ports
        - https-webhook (Port 443, Target-port webhook)

**Comment by tomondre** [comment]
In case the only two requirements are: expose service via HTTPS. I would advise you to follow this guide. It does not include creation of an ingress resource nor ingress controller. It is the simplest way how to expose a service. https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard

**Comment by tomondre** [comment]
When you set Service type to LoadBalancer, a new Load Balancer will be provisioned in your Azure account that will be able to direct the traffic to your pods.

**Comment by PaulMarisOUMary** [comment]
Thank you for the hint, the major issue I encounter is that I'm not able to use the azure CLI and connect to my kubectl environment to send commands. 

I feel I'm about to barely deploy everything the right way using the tutorial from Digital Ocean.
It seems the webhook has the wrong URL:
- Expected: `https://ingress-nginx-controller-admission.k8s-xmas-workflow.svc/networking/v1/ingresses?timeout=10s`
- Current: `https://k8s-xmas-workflow-controller-admission.k8s-xmas-workflow.svc/networking/v1/ingresses?timeout=10s`

From the [workflow error](https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/actions/runs/3693191130/jobs/6253051599#step:5:120):
```bash
Error from server (InternalError): error when creating "/tmp/xmas-ingress.yml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "[https://k8s-xmas-workflow-controller-admission.k8s-xmas-workflow.svc:443/networking/v1/ingresses?timeout=10s](https://k8s-xmas-workflow-controller-admission.k8s-xmas-workflow.svc/networking/v1/ingresses?timeout=10s)": service "k8s-xmas-workflow-controller-admission" not found
```
Do you know a way to change the webhook URL in [.k8s/xmas-ressource.yml](https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/blob/main/.k8s/xmas-ressource.yml)

**Comment by PaulMarisOUMary** [comment]
Well, I follow the [Step 4 from DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes#:~:text=secure%20HTTPS%20protocol.-,Step%204%20%E2%80%94%20Installing%20and%20Configuring%20Cert%2DManager,-In%20this%20step)

The workflow now, raise [this error](https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/actions/runs/3694159397/jobs/6255107573#step:5:156):
```bash
the namespace from the provided object "cert-manager" does not match the namespace "ingress-nginx". You must pass '--namespace=cert-manager' to perform this operation.
```
It seems normal and understandable, however I don't know how to change the context when the workflow try to apply the [.k8s/xmas-cert.yml](https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/blob/main/.k8s/xmas-cert.yml) manifest.
I need to change the namespace during the apply of this specific manifest.

Otherwise I would need to access it through the CLI, but for some reason, it can't find the Azure RessourceGroup we're sharing among us, using my account.
Using:
```
$ az login
$ aks get-credentials --name SantaKubernetes --resource-group prj5
>>> (ResourceGroupNotFound) Resource group 'prj5' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'prj5' could not be found.

**Comment by PaulMarisOUMary** [comment]
Everything is configured now.

Services:
![image](https://user-images.githubusercontent.com/71769515/207675933-8d8b1164-1cb3-4fdf-a952-9d261747d95d.png)

Ingresses:
![image](https://user-images.githubusercontent.com/71769515/207676184-2b1f011f-53bd-467d-afbb-607ff7e75210.png)

We're not linked yet to xmas.algosup.com so I can't make sure everything is working properly.

Anyway do you think of the 404 error on [20.81.0.63](http://20.81.0.63) is normal ? May it due to the DNS not yet linked to our IP adress ? @tomondre

**Comment by tomondre** [comment]
404 is most likely returned from nginx, which is a good sign. There are two possibilities of why the 404 is returned: 
1. The pod that you have deployed does not have any site configured on the url that you have called (for example "/")
2. The ingress is not configured correctly - either the host is wrong or the service that you proxy the traffic to does not exist.

**Comment by tomondre** [comment]
In ingress you have configured:  - host: xmas.algosup.com
That means that you need to call the load balancer via this dns - you should create a xmas.algosup.com
 CNAME with value of dns record of your load balancer.

**Comment by PaulMarisOUMary** [comment]
Since I'm not the owner of `xmas.algosup.com`, and I need to request the DNS to be changed, I changed the host to `xmas.warn.page`(domain name that I own) so I'll be able to test more often.

Right now I've changed the host:
https://github.com/algosup/2022-2023-project-2-santa-time-Project-5-group/blob/a1f4f7fff52345ba999bd752efac020a6ad750e7/.k8s/xmas-ingress.yml#L10-L14

And here are the DNS records:
![image](https://user-images.githubusercontent.com/71769515/207864534-ab335cb8-ef02-4e13-852f-dd317ae9eb07.png)
I assumed that the External IP of my LoadBalancer was the right one to link with CNAME record, but I'm not sure.
![image](https://user-images.githubusercontent.com/71769515/207865310-cbcd2b2b-0933-4128-b97e-395cd2ce31d1.png)


I also noticed that [xmas.algosup.com](http://xmas.algosup.com/) now return a 503 error.

**Comment by tomondre** [comment]
CNAME points to another dns record - it cannot point to an ip address. To make the xmas.warn.page record correct, you should use xmas.warn.page A record to be pointed to 20.81.0.63

**Comment by tomondre** [comment]
After you do that, you should get the same result from both records: xmas.warn.page, xmas.algosup.com

**Comment by PaulMarisOUMary** [comment]
Thanks for your help, on behalf of the entire team😃

<details><summary></summary>

I also want to apologize about the way we have deployed our solution, and our bad practices.

I'm 200% aware of it, and I would have especially loved a real continuous integration, and above all using preview deployment on pull request to avoid errors on main.

We were in a rush, we'll do better next time. 🚀 

</details>
